apiVersion: xl-deploy/v1
kind: Environments
spec:
  - directory: Environments/devDir
    children:
      - name: envTest
        type: udm.Environment
        members:
          - Infrastructure/devDir/infraTest
      - name: qeEnv
        type: udm.Environment
        members:
          - Infrastructure/devDir/qe-controller-6
