apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - directory: Infrastructure/devDir
    children:
      - name: infraTest
        type: overthere.LocalHost
        os: UNIX
        copyStrategy: Tar
      - name: qe-controller-6
        type: overthere.SshHost
        os: UNIX
        address: qe-deploy-controller3.xebialabs.com
